name: build
on:
  push:
    branches:
      - master # 这里表示push到main分支就会触发流程
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0-rc.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Build
        run: |
          pnpm install
          pnpm build  # 执行打包